"""
PDF Report Generator for OSINT Bomber
Uses FPDF library to create professional PDF reports
"""

from fpdf import FPDF
import os
from datetime import datetime

class PDFReport:
    def __init__(self, username, results, email_check=None):
        self.username = username
        self.results = results
        self.email_check = email_check
        self.found_count = len(results)
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    def generate(self):
        """Generate PDF report and save to file"""
        pdf = FPDF()
        pdf.add_page()
        
        # ===== Header =====
        pdf.set_font("Arial", "B", 24)
        pdf.set_text_color(0, 102, 204)
        pdf.cell(0, 20, "OSINT BOMBER REPORT", ln=True, align="C")
        
        pdf.set_font("Arial", "I", 12)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 10, f"Generated: {self.timestamp}", ln=True, align="C")
        pdf.cell(0, 10, f"Username: {self.username}", ln=True, align="C")
        pdf.line(10, 50, 200, 50)
        pdf.ln(15)
        
        # ===== Statistics =====
        pdf.set_font("Arial", "B", 16)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "SCAN STATISTICS", ln=True)
        pdf.set_font("Arial", "", 12)
        pdf.cell(0, 8, f"Total Profiles Found: {self.found_count}", ln=True)
        pdf.cell(0, 8, f"Total Sites Scanned: 55", ln=True)
        pdf.cell(0, 8, f"Scan Date: {self.timestamp}", ln=True)
        pdf.ln(10)
        pdf.line(10, 100, 200, 100)
        pdf.ln(10)
        
        # ===== Results Table =====
        pdf.set_font("Arial", "B", 16)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "PROFILES FOUND", ln=True)
        pdf.ln(5)
        
        # Table Header
        pdf.set_font("Arial", "B", 10)
        pdf.set_fill_color(0, 102, 204)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(80, 10, "Platform", 1, 0, "C", 1)
        pdf.cell(100, 10, "Profile URL", 1, 1, "C", 1)
        
        # Table Body
        pdf.set_font("Arial", "", 9)
        pdf.set_text_color(0, 0, 0)
        fill = False
        for site, url in self.results.items():
            pdf.set_fill_color(240, 240, 240)
            pdf.cell(80, 8, site, 1, 0, "L", fill)
            pdf.cell(100, 8, url, 1, 1, "L", fill)
            fill = not fill
        
        pdf.ln(10)
        pdf.line(10, pdf.get_y() + 20, 200, pdf.get_y() + 20)
        
        # ===== Email Check =====
        if self.email_check:
            pdf.ln(10)
            pdf.set_font("Arial", "B", 16)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 10, "EMAIL BREACH CHECK", ln=True)
            pdf.ln(5)
            pdf.set_font("Arial", "", 11)
            pdf.multi_cell(0, 8, self.email_check)
        
        # ===== Footer =====
        pdf.ln(15)
        pdf.line(10, pdf.get_y() + 10, 200, pdf.get_y() + 10)
        pdf.ln(8)
        
        pdf.set_font("Arial", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 8, "OSINT Bomber v2.0 | Ethical Hacking Tool | For Educational Purposes Only", ln=True, align="C")
        pdf.cell(0, 8, "Generated by Python + FPDF", ln=True, align="C")
        pdf.cell(0, 8, "GitHub: [Your Repo Link]", ln=True, align="C")
        
        # ===== Save PDF =====
        os.makedirs("output", exist_ok=True)
        filename = f"output/report_{self.username}.pdf"
        pdf.output(filename)
        return filename